version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:921804430233:task-definition/ecs-lab:1
        LoadBalancerInfo:
          ContainerName: "sample-website"
          ContainerPort: 80